set DB_PASSWORD={INSERT MONGODB PASSWORD HERE}
set API_KEY={INSERT GOOGLE BOOKS API KEY HERE}
set AZURE_STORAGE_ACCOUNT_NAME={INSERT AZURE STORAGE ACCOUNT NAME HERE}
set SAS_TOKEN={INSERT AZURE STORAGE SAS TOKEN HERE}
node server/index.js